<a href="https://colab.research.google.com/github/komalk98/udemydata/blob/main/udemydt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Udemy Courses Dataset is analyzed**

In [1]:
import pandas as pd

In [2]:
udmy = pd.read_csv('/content/sample_data/Udemydata.csv')

In [3]:
udmy

      course_id  ...              subject
0        288942  ...  Musical Instruments
1       1170074  ...  Musical Instruments
2       1193886  ...  Musical Instruments
3       1116700  ...  Musical Instruments
4       1120410  ...  Musical Instruments
...         ...  ...                  ...
3677     328960  ...      Web Development
3678     552700  ...  Musical Instruments
3679     631754  ...      Web Development
3680    1225194  ...     Business Finance
3681     964478  ...       Graphic Design

[3682 rows x 11 columns]

In [4]:
udmy.isnull().sum()

course_id              0
course_title           0
is_paid                0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
content_duration       0
published_timestamp    0
subject                0
dtype: int64

# **What are all different subjects for which Udemy is offering courses ?**

In [5]:
# udmy.subject.unique()
udmy.groupby('subject')['subject'].count()

subject
Business Finance       1199
Graphic Design          603
Musical Instruments     680
Web Development        1200
Name: subject, dtype: int64

# **subject has the maximum number of courses.**

In [6]:
udmy.subject.value_counts()

Web Development        1200
Business Finance       1199
Musical Instruments     680
Graphic Design          603
Name: subject, dtype: int64

In [7]:
udmy.head(5)

   course_id  ...              subject
0     288942  ...  Musical Instruments
1    1170074  ...  Musical Instruments
2    1193886  ...  Musical Instruments
3    1116700  ...  Musical Instruments
4    1120410  ...  Musical Instruments

[5 rows x 11 columns]

# **courses which are freee**

In [8]:
udmy[udmy['price'] == 'Free']

      course_id  ...              subject
41       286070  ...  Musical Instruments
49       696630  ...  Musical Instruments
57       955914  ...  Musical Instruments
67       270976  ...      Web Development
74      1214144  ...     Business Finance
...         ...  ...                  ...
3620     552598  ...      Web Development
3638    1068590  ...      Web Development
3652     752706  ...      Web Development
3674    1257976  ...  Musical Instruments
3680    1225194  ...     Business Finance

[310 rows x 11 columns]

# courses which are paid **bold text**

In [9]:
udmy[udmy['price'] != 'Free']

      course_id  ...              subject
0        288942  ...  Musical Instruments
1       1170074  ...  Musical Instruments
2       1193886  ...  Musical Instruments
3       1116700  ...  Musical Instruments
4       1120410  ...  Musical Instruments
...         ...  ...                  ...
3676     498488  ...     Business Finance
3677     328960  ...      Web Development
3678     552700  ...  Musical Instruments
3679     631754  ...      Web Development
3681     964478  ...       Graphic Design

[3372 rows x 11 columns]

# **Top selling courses**

In [10]:
udmy.sort_values(by = 'num_subscribers', ascending=False).head(10)

      course_id  ...              subject
2230      41295  ...      Web Development
776       59014  ...      Web Development
3385     625204  ...      Web Development
640      173548  ...      Web Development
3316     764164  ...      Web Development
1388      19421  ...  Musical Instruments
3556     473160  ...      Web Development
2233      94430  ...      Web Development
2886     130064  ...      Web Development
2034     364426  ...      Web Development

[10 rows x 11 columns]

# all courses of Graphic Design where the price is below **100**

In [11]:
udmy[(udmy['subject'] == 'Graphic Design') & (udmy['price'] == '100')]

      course_id  ...         subject
47      1269190  ...  Graphic Design
169      983444  ...  Graphic Design
184      638040  ...  Graphic Design
520      978462  ...  Graphic Design
699      757900  ...  Graphic Design
1029    1160004  ...  Graphic Design
1071    1161864  ...  Graphic Design
1444     490392  ...  Graphic Design
1568     727510  ...  Graphic Design
1616     996868  ...  Graphic Design
1697     654038  ...  Graphic Design
1773    1012262  ...  Graphic Design
1786    1246168  ...  Graphic Design
1797    1266468  ...  Graphic Design
2137     927186  ...  Graphic Design
2481    1027080  ...  Graphic Design
2491     771044  ...  Graphic Design
2576     482924  ...  Graphic Design
2704     950894  ...  Graphic Design
2706    1243016  ...  Graphic Design
2713    1147664  ...  Graphic Design
3479     575040  ...  Graphic Design
3594     908664  ...  Graphic Design

[23 rows x 11 columns]

# all the courses that are related to 'Python'.**bold text**

In [12]:
udmy.head()

   course_id  ...              subject
0     288942  ...  Musical Instruments
1    1170074  ...  Musical Instruments
2    1193886  ...  Musical Instruments
3    1116700  ...  Musical Instruments
4    1120410  ...  Musical Instruments

[5 rows x 11 columns]

In [13]:
udmy[udmy.course_title.str.contains('Python')]

      course_id  ...           subject
216      599504  ...   Web Development
777       47963  ...   Web Development
814      631128  ...   Web Development
842      186096  ...   Web Development
1400     394832  ...   Web Development
1932    1038538  ...   Web Development
1969     902888  ...  Business Finance
2294     391546  ...   Web Development
2295    1063722  ...   Web Development
2341     546848  ...    Graphic Design
2906     368340  ...   Web Development
2908    1035940  ...   Web Development
2929     270808  ...   Web Development
2952    1170894  ...  Business Finance
2953    1070886  ...  Business Finance
2954    1196544  ...  Business Finance
2955     822444  ...   Web Development
2956     477702  ...   Web Development
2957    1035472  ...  Business Finance
2958     529828  ...  Business Finance
2959      70640  ...   Web Development
2960     523312  ...   Web Development
2962    1088656  ...  Business Finance
3013     970600  ...   Web Development
3154     815482  ...  Business Finance
3272     938560  ...   Web Development
3460      76052  ...   Web Development
3573      16646  ...   Web Development
3574     574082  ...   Web Development

[29 rows x 11 columns]

# courses that were published in the year **2015**

In [14]:
udmy['published_timestamp'] = pd.to_datetime(udmy.published_timestamp)

In [15]:
udmy['year'] = udmy['published_timestamp'].dt.year

In [16]:
udmy

      course_id  ...  year
0        288942  ...  2014
1       1170074  ...  2017
2       1193886  ...  2017
3       1116700  ...  2017
4       1120410  ...  2017
...         ...  ...   ...
3677     328960  ...  2015
3678     552700  ...  2015
3679     631754  ...  2015
3680    1225194  ...  2017
3681     964478  ...  2016

[3682 rows x 12 columns]

In [18]:
udmy[udmy.year == 2015]

      course_id  ...  year
10       591880  ...  2015
16       302450  ...  2015
19       384928  ...  2015
23       550842  ...  2015
26       486240  ...  2015
...         ...  ...   ...
3675     551170  ...  2015
3676     498488  ...  2015
3677     328960  ...  2015
3678     552700  ...  2015
3679     631754  ...  2015

[1014 rows x 12 columns]

In [19]:
udmy.groupby('level')['num_subscribers'].max()

level
All Levels            268923
Beginner Level        161029
Expert Level            5172
Intermediate Level     29167
Name: num_subscribers, dtype: int64

In [20]:
udmy.groupby('level').max()

                    course_id  ...  year
level                          ...
All Levels            1277924  ...  2017
Beginner Level        1282064  ...  2017
Expert Level          1275790  ...  2017
Intermediate Level    1276182  ...  2017

[4 rows x 11 columns]